import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { AuthProvider } from "@/providers/auth-provider";
import { ProviderProvider } from "../providers/providerMedicPrac-provider";
import { PatientProvider } from "../providers/paitient-provider";
import { UserProvider } from "../providers/users-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const HealthColors = {
  token: {
    colorPrimary: "#185e67",
    colorInfo: "#185e67",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={HealthColors}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {/* <AuthProvider>
          <ProviderProvider>
            <PatientProvider>
              <UserProvider>{children}</UserProvider>
            </PatientProvider>
          </ProviderProvider>
        </AuthProvider> */}
          <UserProvider>
            <AuthProvider>
              <ProviderProvider>
                <PatientProvider>{children}</PatientProvider>
              </ProviderProvider>
            </AuthProvider>
          </UserProvider>
        </body>
      </html>
    </ConfigProvider>
  );
}
