services:
  abp_host:
    image: abp/host
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__Default: "Server=tcp:healthappserver27.database.windows.net,1433; Database=HealthAPPDb; User Id=sqladmin; Password=MySecurePass123!; TrustServerCertificate=True; Encrypt=True;"
      App__ServerRootAddress: "http://localhost:44311/"
      App__ClientRootAddress: "http://localhost:4200/"
      App__CorsOrigins: "http://localhost:4200"
      TZ: "America/Toronto"
      Kestrel__Endpoints__Http__Url: "http://+:80"
    ports:
      - "44311:80"
    volumes:
      - ./dataProtectionKeys:/root/.aspnet/DataProtection-Keys
    restart: always
 
  abp_ng:
    image: abp/ng
    ports:
      - "4200:80"